myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    path('post_list', views.PostList.as_view(), name='post_list'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path('category_detail/<str:name_en>',
         views.CategoryDetail.as_view(), name='category_detail'),
    path('search', views.Search, name='search'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category=self).count()
        return n

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('タイトル', max_length=50)
    content = models.TextField('内容', max_length=1000)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    def like_count(self):
        n = Like.objects.filter(post=self).count()
        return n

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.PROTECT)
    user = models.ForeignKey(
        User, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Post
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'thumbnail')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class SearchForm(forms.Form):
    freeword = forms.CharField(
        min_length=1, max_length=30, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

myapp/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, resolve_url
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        post = Post.objects.get(id=self.kwargs['pk'])
        return post.author == self.request.user


class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')[:6]
        context = {
            'post_list': post_list,
        }
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Postを登録しました。')
        return resolve_url('myapp:index')


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs['pk'])
        category_posts = Post.objects.filter(
            category=detail_data.category).order_by('-created_at')[:5]
        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }
        return params


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, 'Postを更新しました。')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])


class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.info(self.request, 'Postを削除しました。')
        return resolve_url('myapp:index')


class PostList(ListView):
    model = Post
    # ページネーション
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'


class Logout(LogoutView):
    template_name = 'myapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.info(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id=post_id)
    is_liked = Like.objects.filter(user=request.user, post=post_id).count()
    if is_liked > 0:
        messages.info(request, 'すでにお気に入りに追加済みです。')
        return redirect('myapp:post_detail', post_id)
    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, 'お気に入りに追加しました！')
    return redirect('myapp:post_detail', post.id)


class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs['name_en'])
        category_posts = Post.objects.filter(
            category=detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }
        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = Post.objects.filter(
                Q(title__icontains=freeword) | (Q(content__icontains=freeword)))

        params = {
            'search_list': search_list,
        }
        return render(request, 'myapp/search.html', params)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta http-equiv="x-ua-compatible" content="ie=edge" />
	<title>{{ request.site.siteconfig.meta_title }}</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<!-- Font Awesome -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
	<!-- MDB -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.0/mdb.min.css" rel="stylesheet" />

	<!-- <link href="./style.css" rel="stylesheet"> -->
</head>

<body>
	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<!-- Container wrapper -->
		<div class="container-fluid">
			<!-- Toggle button -->
			<button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
				data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<i class="fas fa-bars"></i>
			</button>

			<!-- Collapsible wrapper -->
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<!-- Navbar brand -->
				<a class="navbar-brand mt-2 mt-lg-0" href="/">
					<img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="15" alt=""
						loading="lazy" />
				</a>
				<!-- Left links -->
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/admin" target="_blank">管理画面へ</a>
					</li>
					<!-- Dropdown -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
							data-mdb-toggle="dropdown" aria-expanded="false">
							Account
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							{% if request.user.is_authenticated %}
							<li>
								<a class="dropdown-item" href="">{{ request.user }}</a>
							</li>
							<li>
								<a class="dropdown-item" href="{% url 'myapp:logout' %}">ログアウト</a>
							</li>
							{% else %}
							<li>
								<a class="dropdown-item" href="{% url 'myapp:login' %}">ログイン</a>
							</li>
							<li>
								<a class="dropdown-item" href="{% url 'myapp:signup' %}">ユーザ登録</a>
							</li>
							{% endif %}
						</ul>
					</li>
					<!-- Dropdown -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
							data-mdb-toggle="dropdown" aria-expanded="false">
							Post
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li>
								<a class="dropdown-item" href="{% url 'myapp:post_create' %}">新規投稿</a>
							</li>
							<li>
								<a class="dropdown-item" href="{% url 'myapp:post_list' %}">投稿一覧</a>
							</li>
						</ul>
					</li>
					<!-- Dropdown -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
							data-mdb-toggle="dropdown" aria-expanded="false">
							Category
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							{% for item in category_list %}
							<li>
								<a class="dropdown-item" href="{% url 'myapp:category_detail' item.name_en %}">{{ item.name }}</a>
							</li>
							{% endfor %}
							<hr>
							<li>
								<a class="dropdown-item" href="{% url 'myapp:category_list' %}">カテゴリ一覧</a>
							</li>
						</ul>
					</li>
				</ul>
				<!-- Left links -->
			</div>
			<!-- Collapsible wrapper -->

			<!-- Right elements -->
			<div class="d-flex align-items-center">
				<form action="{% url 'myapp:search' %}" class="form-inline" method="POST">
					{% csrf_token %}
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" ,
						name="freeword">
				</form>
			</div>
			<!-- Right elements -->
		</div>
		<!-- Container wrapper -->
	</nav>
	<!-- Navbar -->
	<main class="container">

		{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }}" role="alert">
			{{ message }}
		</div>
		{% endfor %}
		{% endif %}

		{% block content %}
		{% endblock content %}
	</main>
	<!-- Footer -->
	<footer class="text-center text-lg-start bg-light text-muted">
		<!-- Section: Social media -->
		<section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
			<!-- Left -->
			<div class="me-5 d-none d-lg-block">
				<span>Get connected with us on social networks:</span>
			</div>
			<!-- Left -->

			<!-- Right -->
			<div>
				<a href="" class="me-4 text-reset">
					<i class="fab fa-facebook-f"></i>
				</a>
				<a href="" class="me-4 text-reset">
					<i class="fab fa-twitter"></i>
				</a>
				<a href="" class="me-4 text-reset">
					<i class="fab fa-google"></i>
				</a>
				<a href="" class="me-4 text-reset">
					<i class="fab fa-instagram"></i>
				</a>
				<a href="" class="me-4 text-reset">
					<i class="fab fa-linkedin"></i>
				</a>
				<a href="" class="me-4 text-reset">
					<i class="fab fa-github"></i>
				</a>
			</div>
			<!-- Right -->
		</section>
		<!-- Section: Social media -->

		<!-- Section: Links  -->
		<section class="">
			<div class="container text-center text-md-start mt-5">
				<!-- Grid row -->
				<div class="row mt-3">
					<!-- Grid column -->
					<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
						<!-- Content -->
						<h6 class="text-uppercase fw-bold mb-4">
							<i class="fas fa-gem me-3"></i>Company name
						</h6>
						<p>
							Here you can use rows and columns to organize your footer content. Lorem ipsum
							dolor sit amet, consectetur adipisicing elit.
						</p>
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
						<!-- Links -->
						<h6 class="text-uppercase fw-bold mb-4">
							Products
						</h6>
						<p>
							<a href="#!" class="text-reset">Angular</a>
						</p>
						<p>
							<a href="#!" class="text-reset">React</a>
						</p>
						<p>
							<a href="#!" class="text-reset">Vue</a>
						</p>
						<p>
							<a href="#!" class="text-reset">Laravel</a>
						</p>
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
						<!-- Links -->
						<h6 class="text-uppercase fw-bold mb-4">
							Useful links
						</h6>
						<p>
							<a href="#!" class="text-reset">Pricing</a>
						</p>
						<p>
							<a href="#!" class="text-reset">Settings</a>
						</p>
						<p>
							<a href="#!" class="text-reset">Orders</a>
						</p>
						<p>
							<a href="#!" class="text-reset">Help</a>
						</p>
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
						<!-- Links -->
						<h6 class="text-uppercase fw-bold mb-4">
							Contact
						</h6>
						<p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
						<p>
							<i class="fas fa-envelope me-3"></i>
							info@example.com
						</p>
						<p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
						<p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
					</div>
					<!-- Grid column -->
				</div>
				<!-- Grid row -->
			</div>
		</section>
		<!-- Section: Links  -->

		<!-- Copyright -->
		<div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
			© 2021 Copyright:
			<a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
		</div>
		<!-- Copyright -->
	</footer>
	<!-- Footer -->


	<!-- MDB -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.0/mdb.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
		crossorigin="anonymous"></script>
	<!-- Custom scripts -->
	<script type="text/javascript"></script>
</body>

</html>

myapp/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-9">
		<br>
		<h2>{{ object.name }}</h2>
		<hr>
		<ul class="list-group">
			{% for item in category_posts %}
			<li class="list-group-item"><a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a></li>
			{% endfor %}
		</ul>
		<br><br>
	</div>
</div>

{% endblock content %}

myapp/templates/myapp/category_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-9">
		<br>
		<h2>Category list</h2>
		<br>
	</div>
</div>
<div class="row">
	{% for category in category_list %}
	<div class="col-md-4">
		<br>
		<div class="card">
			<div class="card-body">
				<h4 class="card-title"><a href="{% url 'myapp:category_detail' category.name_en %}">{{ category.name }}</a>&nbsp;<small>[&nbsp;{{ category.post_count }}&nbsp;]</small></h4>
				<hr>
				{% for post in category.post_set.all|slice:5 %}
				<p><a href="{% url 'myapp:post_detail' post.id %}" style="color:black;">{{ post.title }}</a></p>
				{% endfor %}
				<br>
				<a href="{% url 'myapp:category_detail' category.name_en %}">このカテゴリの記事を全て見る</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
<br>

{% endblock content %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
<br>
<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1 class="display-4">{{ request.site.siteconfig.top_title }}</h1>
		<p class="lead">{{ request.site.siteconfig.top_subtitle }}</p>
	</div>
</div>

<div class="row">
	<div class="card-deck">
		{% for item in post_list %}
		<div class="col-md-4">
			<div class="card mb-4">

				<div class="view overlay">
					{% if item.thumbnail %}
					<img src="{{ item.thumbnail.url }}" class="card-img-top" alt="{{ item.title }}" />
					{% else %}
					<img src="https://mdbootstrap.com/img/new/standard/city/044.jpg" class="card-img-top" alt="..." />
					{% endif %}
					<a href="{% url 'myapp:post_detail' item.id %}">
						<div class="mask rgba-white-slight"></div>
					</a>
				</div>

				<div class="card-body">
					<h4 class="card-title">{{ item.title }}</h4>
					<p>{{ item.category }}</p>
					<p class="card-text">{{ item.content | safe | truncatechars_html:12 }}</p>
					<a href="{% url 'myapp:post_detail' item.id %}" type="button"
						class="btn btn-light-blue btn-md">もっと読む</a>
					<i class="fas fa-heart" style="color:pink;"></i>&nbsp;{{ item.like_count }}
				</div>
				<!-- card footer -->
				<div class="card-footer text-muted text-center mt-4">
					<small>by&nbsp;{{ item.author }}&nbsp;at {{ item.created_at.date }}</small>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	<br>
</div>
<a class="btn btn-outline-default waves-effect" href="{% url 'myapp:post_list' %}">全ての記事を見る</a>
<br>
<br>
{% endblock content %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<br>
		<h2>Login</h2>
		<br>
		<form action="" method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{% for field in form %}
			{{ field.label }}
			{{ field }}
			{{ field.errors }}
			{% endfor %}
			<button type="submit" class="btn btn-primary">保存</button>
			<br>
		</form>
	</div>
</div>

{% endblock content %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<br>
		<h2>Logout</h2>
		<br>
		<p>ログアウトしました</p>
	</div>
</div>

{% endblock content %}

myapp/templates/myapp/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page_obj.has_previous %}
		<a href="?page=1">&laquo; first</a>
		<a href="?page={{ page_obj.previous_page_number }}">previous</a>
		{% endif %}

		<span class="current">
			Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
		</span>

		{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}">next</a>
		<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
		{% endif %}
	</span>
</div>

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-9">
		<br>
		<h2>削除</h2>
		<br>
		<div class="alert alert-danger" role="alert">
			<form method="post">
				{% csrf_token %}
				<p>以下の内容を本当に削除しますか？</p>
				<input type="submit" class="btn btn-danger" value="削除する">
			</form>
		</div>
		<br>
		<p>タイトル</p>
		{{ object.title }}
		<hr>
		<p>内容</p>
		{{ object.content }}
	</div>
	<br class="br">
</div>

{% endblock content %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<br>
<div class="row">
	<br>
	<div class="col-md-9">

		<div class="card">
			{% if object.thumbnail %}
			<img src="{{ object.thumbnail.url }}" class="card-img-top" alt="{{ object.title }}" />
			{% else %}
			<img src="https://mdbootstrap.com/img/new/standard/nature/184.jpg" class="card-img-top" alt="..." />
			{% endif %}
			<div class="card-body">
				<h5 class="card-title">{{ object.title }}</h5>
				<p class="card-text">{{ object.content | safe | linebreaksbr | urlize }}</p>
				<a class="btn" href="{% url 'myapp:like_add' object.pk %}"
					style="background-color:#FF6699; color:white;">お気に入りに入れる</a>
				<small>{% if object.like_count %}{{ object.like_count }}人がお気に入りに入れています。{% endif %}</small>
				<hr>
				<a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-outline-dark">戻る</a>
				{% if object.author == request.user %}
				<a href="{% url 'myapp:post_update' object.pk %}" class="btn btn-primary">更新</a>
				<a href="{% url 'myapp:post_delete' object.pk %}" class="btn btn-danger">削除</a>
				{% endif %}
			</div>
			<!-- card footer -->
			<div class="card-footer text-muted text-center mt-4">
				<small>by&nbsp;{{ object.author }}&nbsp;at {{ object.created_at.date }}</small>
			</div>
		</div>	
		<br>
	</div>
	<div class="col-md-3">
		<br>
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">{{ object.category }}</h5>
				<p>このカテゴリの他の記事</p>
			</div>
			<ul class="list-group">
				{% for item in category_posts %}
				<li class="list-group-item"><a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-9">
		<br>
		<h2>Post登録・更新</h2>
		<br>

		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-group">
				<label>タイトル</label>
				{{ form.title }}
			</div>
			<div class="form-group">
				<label>カテゴリー</label>
				{{ form.category }}
			</div>
			<div class="form-group">
				<label>サムネイル画像</label>
				{{ form.thumbnail }}
			</div>
			<br>
			<div class="form-group">
				<label>内容</label>
				{{ form.content }}
			</div>
			<br>
			<button type="submit" class="btn btn-primary">保存</button>
			<br><br>
		</form>
	</div>
</div>

{% endblock content %}

myapp/templates/myapp/post_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<br>
		<h2>Post一覧</h2>
		<br>
		<table class="table">
			<thead>
				<tr>
					<th width="200px">タイトル</th>
					<th>内容</th>
					<th width="200px">作成日時<br>更新日時</th>
				</tr>
			</thead>
			<tbody>
				{% for item in post_list %}
				<tr>
					<td><a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a></td>
					<td>{{ item.content|safe|truncatechars_html:30 }}</td>
					<td>{{ item.created_at }}<br>{{ item.updated_at }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<br>
		{% include 'myapp/pagination.html' %}
		<br>
	</div>

</div>

{% endblock content %}

myapp/templates/myapp/search.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<br>
		<h2>Post一覧</h2>
		<br>
		<table class="table">
			<thead>
				<tr>
					<th width="200px">タイトル</th>
					<th>内容</th>
					<th width="200px">作成日時<br>更新日時</th>
				</tr>
			</thead>
			<tbody>
				{% for item in search_list %}
				<tr>
					<td><a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a></td>
					<td>{{ item.content|safe|truncatechars_html:30 }}</td>
					<td>{{ item.created_at }}<br>{{ item.updated_at }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<br>
		{% include 'myapp/pagination.html' %}
		<br>
	</div>

</div>

{% endblock content %}

myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<br>
		<h2>SignUp</h2>
		<br>
		<form action="" method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{% for field in form %}
			{{ field.label }}
			{{ field }}
			{{ field.errors }}
			{% endfor %}

			<button type="submit" class="btn btn-primary">SignUp</button>
			<br>
		</form>
	</div>
</div>

{% endblock content %}